spring:
  application:
    name: 'dental-clinic-api'

  # H2 Database Configuration for Development
  datasource:
    url: jdbc:h2:mem:dental_clinic_db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop # Recreates tables on each startup for development
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  # Security Configuration (disabled for H2 console)
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging Configuration
logging:
  level:
    com.dentalclinic: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
