spring:
  datasource:
    url: jdbc:sqlserver://localhost\\SQLEXPRESS01;databaseName=dentalclinicdb;encrypt=false;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
