spring:
  application:
    name: dentalclinic-api

  # Database Configuration (MSSQL Server)
  datasource:
    # MSSQL Server với SQL Authentication
    url: jdbc:sqlserver://localhost:1433;databaseName=DentalClinicDB;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: admin123

    # Nếu dùng Windows Authentication, thay bằng config này:
    # url: jdbc:sqlserver://localhost:1433;databaseName=DentalClinicDB;integratedSecurity=true;encrypt=true;trustServerCertificate=true
    # username:
    # password:
    # Lưu ý: Cần copy sqljdbc_auth.dll vào System32 hoặc thêm vào PATH

  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update # Tự động tạo/update tables (đổi thành 'validate' khi production)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

# JWT Configuration
jwt:
  secret: MyVerySecureSecretKeyForDentalClinicManagementSystemAtLeast256BitsLong12345
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Logging Configuration
logging:
  level:
    com.dentalclinic: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
