spring:
  application:
    name: 'dental-clinic-api'

  # Database Configuration - Using H2 for quick setup
  # Switch to MySQL configuration when ready for production
  datasource:
    url: jdbc:h2:mem:dental_clinic_db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # H2 Console Configuration (for development only)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop # Creates tables automatically
    show-sql: true # Shows SQL queries in console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  # Security Configuration
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    com.dentalclinic: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    config-url: /v3/api-docs/swagger-config
    urls-primary-name: Dental Clinic API
    doc-expansion: none
    default-models-expand-depth: -1
    default-model-expand-depth: -1
  show-actuator: false
  use-management-port: false

---
# MySQL Configuration (uncomment when ready to use MySQL)
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/dental_clinic_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#     username: root
#     password: your_mysql_password_here
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQLDialect
