spring:
  # Database Configuration (MSSQL for production)
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=DentalClinicDB;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: admin123

    # Connection Pool Settings
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update # Tự động update schema
    show-sql: false # Tắt để giảm log
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.SQLServerDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

# Logging Configuration (ít verbose hơn dev)
logging:
  level:
    com.dentalclinic: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
